# Generated by Django 4.0.6 on 2022-07-13 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owener'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='owener',
            new_name='owner',
        ),
    ]
